# 1. 输入：监听 Filebeat 5044端口
input {
  beats {
    port => 5044
    codec => plain { charset => "UTF-8" } # 解决中文乱码
  }
}

# 2. 过滤：清空日志自动丢弃
filter {
  if [message] == "" {
    drop { }
  }
}

# 3. 输出：写入 Elasticsearch
output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "ops-log-%{+YYYY.MM.dd}" # 按天创建索引
    codec => plain { charset => "UTF-8" } # 中文不乱码
  }
  # 控制台打印日志（调试用）
  stdout {
    codec => rubydebug
  }
}
